enum ERole {
  ADMIN
  USER
}

enum EAuthMethod {
  GOOGLE
  CREDENTIAL
}

type TUserAuth {
  userUuid: String!
  accessToken: String!
  refreshToken: String!
}

type TUserInfoResponse {
  uuid: String!
  email: String!
  name: String
  walletAddress: String
  authMethods: [EAuthMethod]!
  address: String
  phoneNumber: String
}

type TConnectCryptoWalletResponse {
  connectCompleted: Boolean!
  userUuid: String!
  walletAddress: String!
}

type Query {
  userInfo: TUserInfoResponse!
  cryptoWalletWithNone: String!
}

type Mutation {
  refreshToken(refreshToken: String!): TUserAuth!
  userRegister(email: String!, password: String!): TUserAuth!
  userLogin(token: String, email: String, password: String): TUserAuth!
  userConnectCryptoWallet(signature: String!, address: String!): TConnectCryptoWalletResponse!
  userLogout(logoutEverywhere: Boolean): Boolean!
}
