enum ERole {
  ADMIN
  USER
}

enum EAuthMethod {
  GOOGLE
  CREDENTIAL
}

type TUserAuth {
  accessToken: String!
  refreshToken: String!
}

type UserInfo {
  uuid: String!
  email: String!
  name: String
  walletAddress: String
  role: ERole!
  authMethod: EAuthMethod!
  address: String
  phoneNumber: String
}

type TConnectCryptoWalletResponse {
  connectCompleted: Boolean!
  userUuid: String!
  walletAddress: String!
}

type Query {
  userInfo: UserInfo!
  cryptoWalletWithNone: String!
}

type Mutation {
  refreshToken(refreshToken: String!): TUserAuth!
  userRegister(email: String!, password: String!): TUserAuth!
  userLogin(token: String, email: String, password: String): TUserAuth!
  userConnectCryptoWallet(signature: String!, address: String!): TConnectCryptoWalletResponse!
  userLogout(logoutEverywhere: Boolean): Boolean!
}
