type TItemOption {
  group: String!
  name: String!
  extraPrice: Float
}

enum EItemStatus {
  NEW
  SELLER
  EMPTY
}

type TItemResponse {
  itemId: String!
  name: String!
  image: String!
  price: Float!
  description: String
  discountPercent: Float
  requireOption: [TItemOption]
  additionalOption: [TItemOption]
  status: [EItemStatus]
  categoryName: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

input ItemOptionInput {
  group: String!
  name: String!
  extraPrice: Float
}

input CreateItemInput {
  name: String!
  image: String!
  price: Float!
  description: String
  discountPercent: Float
  requireOption: [ItemOptionInput]
  additionalOption: [ItemOptionInput]
  status: [EItemStatus]
  categoryName: String!
}

input UpdateItemInput {
  itemId: String!
  name: String
  image: String
  price: Float
  description: String
  discountPercent: Float
  requireOption: [ItemOptionInput]
  additionalOption: [ItemOptionInput]
  status: [EItemStatus]
  categoryName: String
}

type TListItemResponse {
  offset: Int!
  limit: Int!
  total: Int!
  query: [TQueryBy]!
  records: [TItemResponse!]!
}

type Query {
  listItem(offset: Int, limit: Int, query: [QueryByInput]): TListItemResponse!
  itemByCategory(offset: Int, limit: Int, categoryName: String!): TListItemResponse!
  itemById(itemId: String!): TItemResponse!
}

type Mutation {
  createItem(input: CreateItemInput!): TItemResponse!
  updateItem(input: UpdateItemInput!): TItemResponse!
  deleteItem(itemId: String!): Boolean!
}
