enum EPaymentMethod {
  COD
  PAYPAL
  CRYPTO
}

enum EPaymentStatus {
  PENDING
  SUCCESSFUL
  FAILED
}

type TPaymentResponse {
  paymentId: String!
  orderId: String!
  paymentMethod: EPaymentMethod!
  totalPrice: Float!
  status: EPaymentStatus!
  userInfo: TUserInfoSnapshot!
  items: [TOrderItem]!
  txHash: String
  paypalTransactionId: String
  codTransactionId: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type TListPaymentResponse {
  offset: Int!
  limit: Int!
  total: Int!
  query: [TQueryBy]!
  records: [TPaymentResponse]!
}

"""
Input types
"""
input ConfirmPaymentInput {
  orderId: String!
  paymentMethod: EPaymentMethod!
  paypalTransactionId: String
  txHash: String
  codTransactionId: String
}

type Query {
  paymentHistory(paymentId: String!): TPaymentResponse!
  listPaymentHistory(offset: Int, limit: Int, query: [QueryByInput]): TListPaymentResponse!
}

type Mutation {
  confirmPayment(paymentInput: ConfirmPaymentInput!): TPaymentResponse!
}
