enum EPaymentMethod {
  COD
  PAYPAL
  CRYPTO
}

enum EPaymentStatus {
  PROCESSING
  SUCCESS
  FAILED
  CANCELLED
}

type TPaypalPayment {
  paypalPayerEmail: String!
  paypalCaptureId: String!
  payerId: String!
  rawResponse: Object
}

type TUserPaymentResponse {
  paymentId: String!
  orderId: String!
  paymentMethod: EPaymentMethod!
  totalPrice: Float!
  status: EPaymentStatus!
  userInfo: TUserInfoSnapshot!
  items: [TOrderItem!]!
  transactionId: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type TPaymentResponse {
  paymentId: String!
  orderId: String!
  paymentMethod: EPaymentMethod!
  totalPrice: Float!
  status: EPaymentStatus!
  userInfo: TUserInfoSnapshot!
  items: [TOrderItem]!
  txHash: String
  paypalTransaction: TPaypalPayment
  codTransactionId: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type TListPaymentUserResponse {
  offset: Int!
  limit: Int!
  total: Int!
  query: [TQueryBy]!
  records: [TUserPaymentResponse]!
}

type TListPaymentResponse {
  offset: Int!
  limit: Int!
  total: Int!
  query: [TQueryBy]!
  records: [TPaymentResponse]!
}

"""
Input types
"""
input ConfirmPaymentInput {
  orderId: String!
}

type Query {
  paymentUserHistory(paymentId: String!): TUserPaymentResponse!
  listUserPaymentHistory(offset: Int, limit: Int, query: [QueryByInput]): TListPaymentUserResponse!
  listPaymentHistory(offset: Int, limit: Int, query: [QueryByInput]): TListPaymentResponse!
}

type Mutation {
  approveCODPayment(paymentInput: ConfirmPaymentInput!): TPaymentResponse!
}
