enum EOrderStatus {
  CREATED
  PENDING
  PAID
  CANCELLED
  COMPLETED
  FAILED
}

type TUserInfoSnapshot {
  name: String!
  address: String!
  phoneNumber: String!
  email: String!
}

type TOrderItem {
  image: String!
  name: String!
  amount: Int!
  price: Float!
  note: String
  discountPercent: Float
  selectedOptions: [TItemOption!]!
}

type TCreateOrderResponse {
  orderId: String!
  transactionId: String
  paypalApproveUrl: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type TOrderResponse {
  orderId: String!
  transactionId: String
  userInfoSnapshot: TUserInfoSnapshot!
  items: [TOrderItem!]!
  totalPrice: Float!
  paymentMethod: EPaymentMethod!
  orderStatus: EOrderStatus!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type TListOrderResponse {
  offset: Int!
  limit: Int!
  total: Int!
  query: [TQueryBy]!
  records: [TOrderResponse]!
}

"""
Input types
"""
input UserInfoSnapshotInput {
  name: String!
  address: String!
  phoneNumber: String!
  email: String!
}

input OrderItemInput {
  itemId: String!
  amount: Int!
  note: String
  selectedOptions: [ItemOptionInput!]
}

input CreateOrderInput {
  items: [OrderItemInput!]!
  paymentMethod: EPaymentMethod!
  userInfo: UserInfoSnapshotInput!
  returnUrl: String!
  cancelUrl: String!
}

type Query {
  getUserOrder(orderId: String!): TOrderResponse!
  getAllOrder(orderId: String!): TListOrderResponse!
}

type Mutation {
  createOrder(input: CreateOrderInput!): TCreateOrderResponse!
}
